# Generated by Django 4.1.3 on 2022-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_address_id_address_publisher_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SF', 'Science Fiction'), ('R', 'Romance'), ('C', 'Comedy'), ('CR', 'Crime'), ('TC', 'Tragicomedy'), ('T', 'Tragedy')], default='R', max_length=2),
        ),
    ]
