# Generated by Django 4.1.3 on 2022-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('C', 'Comedy'), ('R', 'Romance'), ('SF', 'Science Fiction'), ('CR', 'Crime'), ('T', 'Tragedy'), ('TC', 'Tragicomedy')], default='R', max_length=2),
        ),
    ]
